### ISSUE TITLE
Simple Docker Compose?

### ISSUE THREAD

**Issue by yamisins** [ogarcia/docker-polaris#12]
I have not been able to understand how to do this on docker, unless I am missing stuff their is really not much instructions on how to do this at all, Isnt their a docker compose that can be run or is their better documentation by any chance , this software looks and seems amazing I cannot wait to try. Thanks so much <3

**Comment by ogarcia** [comment]
The truth is that I don't really understand what documentation you are missing that is not in the [Readme](https://github.com/ogarcia/docker-polaris/blob/master/README.md).

A Docker compose is to translate the docker run line to a yaml:
```yaml
services:
  polaris:
    image: registry.gitlab.com/connectical/container/polaris
    ports:
      - "5050:5050"
    volumes:
      - /my/music/directory:/music
      - /my/polaris/cache:/var/cache/polaris
      - /my/polaris/data:/var/lib/polaris
```

What is not working? What error are you getting? Can you be more specific?
